# .github/workflows/pages.yml
name: Deploy static site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS + full history)
        uses: actions/checkout@v4
        with:
          lfs: true          # <— important if you ever track media via Git LFS
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Optional: quick sanity check of what will be deployed
      - name: List key assets
        run: |
          ls -lah .
          ls -lah Outputs || true
          ls -lah Outputs/videos || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .            # deploy repository root (where index.html lives)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
